PasswordManager/PasswordManager/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('manager.urls')),
    path('accounts/generator/', include('generator.urls')),
]

PasswordManager/generator/urls.py
from django.urls import path
from .views import GeneratorFormView


urlpatterns = [
        path('', GeneratorFormView.as_view(), name='generator'),
    ]

PasswordManager/manager/urls.py
from manager.models import Account
from django.urls import path
from .views import LandingPageView, SignUpView, UserLoginView, AccountListView, AddNewAccountView, EditAccountView, AccountDeleteView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', LandingPageView.as_view(), name='index'),

    path('SignUp/', SignUpView.as_view(), name='signup'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),

    path('accounts/', AccountListView.as_view(), name='accounts'),
    path('new_account/', AddNewAccountView.as_view(), name='new_account'),
    path('edit/<str:pk>/', EditAccountView.as_view(), name='edit'), 
    path('delete/<str:pk>', AccountDeleteView.as_view(), name='delete'),
]

PasswordManager/generator/models.py
from django.db import models

# Create your models here.

PasswordManager/manager/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.

class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    url = models.URLField(blank=True)
    username = models.CharField(max_length=100, blank=True)
    password = models.CharField(max_length=100, blank=True)
    email = models.EmailField(blank=True)
    notes = models.TextField(blank=True)

    def __str__(self):
        return self.title

PasswordManager/generator/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column
from crispy_forms.bootstrap import InlineRadios

class PasswordGeneratorForm(forms.Form):

    password = forms.CharField(widget=forms.TextInput(
        attrs={
            'value': '{{ password }}'
            }
        ),)

    OPTIONS = (('lc_letters', 'a-z'), ('uc_letters', 'A-Z'),
            ('numbers', '0-9'), ('symbols', '@%^!...'))
    
    # TODO flattecn checkboxes
    characters = forms.MultipleChoiceField(
            choices=OPTIONS,
            widget=forms.CheckboxSelectMultiple(
                attrs={
                    'class': 'form-check form-check-inline'
                }),
            initial='lc_letters',
            )

    length = forms.CharField(required=True, widget=forms.TextInput(
        attrs={
            'type': 'number',
            'value': '12',
        }
    ))

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.helper = FormHelper()
    #     self.helper.form_method = 'get'

    #     self.helper.layout = Layout(
    #         InlineRadios('characters'),

    #     )

PasswordManager/manager/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm, EmailField
from django.contrib.auth.forms import UserCreationForm

from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, Submit, Field, Fieldset, Layout
from crispy_forms.bootstrap import AppendedText

from .models import Account 



class UserRegistrationForm(UserCreationForm):
    email = EmailField()
    class Meta:
        model = User
        fields = ['username', 'email']


class AccountForm(ModelForm):
    class Meta:
        model = Account
        fields = ['title', 'username', 'email', 'password', 'url', 'notes']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'},),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.TextInput(attrs={'class': 'form-control', 'type': 'password', }), 
            'url': forms.TextInput(attrs={'class': 'form-control'}),
            'notes': forms.Textarea(attrs={'class': 'form-control'}),
        }


    # TODO: start working on modals
    # TODO: password generator app

PasswordManager/generator/views.py
import string
import secrets

from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import PasswordGeneratorForm


class GeneratorFormView(LoginRequiredMixin, FormView):
    template_name = 'generator/generator.html'

    form_class = PasswordGeneratorForm
    
# TODO write GET method for Generator class with the generator logic below
def password(request):

    lc_letters = string.ascii_lowercase
    uc_letters = string.ascii_uppercase
    numbers = string.digits
    symbols = string.punctuation

    length = int(request.GET.get('length', '12'))

    use_chars = lc_letters

    if request.GET.get('uc_letters'):
        use_chars += uc_letters

    if request.GET.get('numbers'):
        use_chars += numbers

    if request.GET.get('symbols'):
        use_chars += symbols

    password = ''.join(secrets.choice(use_chars) for _ in range(length))

    return 

PasswordManager/manager/views.py
import requests
import json
import string
import hashlib
import base64

from django.db import IntegrityError
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import  CreateView, DeleteView, UpdateView, FormView
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from bootstrap_modal_forms.generic import BSModalCreateView

from .forms import AccountForm, UserRegistrationForm
from .models import Account


class LandingPageView(TemplateView):
    template_name = 'manager/index.html'
    model = Account

class SignUpView(SuccessMessageMixin, CreateView):
    template_name = 'manager/sign_up_form.html'
    form_class = UserCreationForm
    success_message = 'Your account was created successfully'
    success_url = reverse_lazy('login')

class UserLoginView(LoginView):
    template_name = 'manager/login_form.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('accounts')
    
class AddNewAccountView(LoginRequiredMixin, CreateView):
    model = Account
    form_class = AccountForm
    template_name = 'manager/add_account.html'
    success_url = reverse_lazy('accounts')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(AddNewAccountView, self).form_valid(form)



# class AddNewAccountView(LoginRequiredMixin, BSModalCreateView):
    # # TODO Modal view
    # pass
#     template_name = 'manager/add_account.html'
#     form_class = AccountForm
#     success_message = 'New account added!'
#     success_url = reverse_lazy('accounts')

#     def form_valid(self, form):
#         form.instance.user = self.request.user
#         return super(AddNewAccountView, self).form_valid(form)


class AccountListView(LoginRequiredMixin, ListView):
    template_name = 'manager/main.html'
    model = Account
    context_object_name = 'accounts'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['accounts'] = context['accounts'].filter(user=self.request.user)
        return context


# class AccountDetailView(LoginRequiredMixin, DetailView):
#     pass


class EditAccountView(LoginRequiredMixin, UpdateView):
    model = Account
    form_class = AccountForm
    template_name = 'manager/edit_account.html'
    success_url = reverse_lazy('accounts')



class AccountDeleteView(LoginRequiredMixin, DeleteView):
    model = Account
    context_object_name = 'account'
    success_url = reverse_lazy('accounts')

PasswordManager/generator/templates/generator/generator.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block page_content %}

<div class="container">
    <form action="GET">
        {% csrf_token %}
        {{ form|crispy }}
    </form>
</div>

{% endblock %}

PasswordManager/manager/templates/base.html
{% load static %}


<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" /> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <title>PW Manager</title>
  </head>
  
  <body>

    {% block page_content %}

    {% endblock %}

    
    <script src="{% static 'js/passwordToggle.js' %}"></script>
    <script src="{% static 'js/copyToClipboard.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </body>
</html>












<!-- Bootstrap 4 -->

<!-- <!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Password Manager</title>
  </head>
  <body>
    

    {#% block page_content %#}

    {#% endblock %#}



    <script src="{% static 'js/main.js' %}"></script>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    
  </body>
</html> -->

PasswordManager/manager/templates/manager/accounts.html
{% extends 'base.html' %}

{% block page_content %}

{% include 'navbar.html' %}


<div class="container">
    
    {% if user.is_authenticated %}

    <h2>Hello {{ user.username|capfirst }}</h2>

    <a class="btn btn-secondary"href="{% url 'new_account' %}">Crete Account</a>
    <br><br>

    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Username</th>
                <th>E-mail</th>
                <th>Password</th>
                <th>URL</th>
                <th>Notes</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for account in accounts %}
            <tr>
                <td>{{ account.title }}</td>
                <td><a class="tc to-clp" href="#" data={{ account.username }}>{{ account.username }}</a></td>
                <td><a class="tc to-clp" href="#" data={{ account.email }}>{{ account.email }}</a></td>


                <td>
                    <a class="tc to-clp" href="#" data={{ account.password }}>*********</a>
                </td>


                <td><a href="{{ account.url }}" target="_blank">{{ account.url }}</a></td> 
                <td>{{ account.notes|slice:":50" }}</td>
                <td>

                    <a class="btn btn-sm btn-secondary" href="{% url 'edit' account.id %}">Edit</a>

                    <form action="{% url 'delete' account.id %}" method="POST" style="display: inline;">
                        {% csrf_token %}
                        <button class="btn btn-danger btn-sm" type="submit" onclick="return confirm('Deleting this account will cause all of the information to be lost.\nDo you wish to continue?')">Delete</button></button>
                    </form>

                </td>
            </tr>

            {% endfor %}
        </tbody>
    </table>

    {% else %}
    <h1>You have no permission to be here</h1>
    {% endif %}
</div>


{% endblock %}

PasswordManager/manager/templates/manager/add_account(modal).html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block page_content %}

<div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalToggleLabel">New account</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">


        <div class="container">
    
          <form action="" method="post">
            {% csrf_token %}
              <div class="wrapper">
                <label for="title">Title</label>
                {{ form.title }}
              </div>
              
              <div class="wrapper">
                <label for="id_username">Username</label>
                {{ form.username }}
              </div>

              <div class="wrapper">
                <label for="id_email">Email</label>
                {{ form.email }}
              </div>
                  
              <div class="wrapper password-field">
                <label for="id_password">Password</label>
                {{ form.password }}
                <span class="toggle-modal dice" data-bs-toggle="modal" data-bs-target="#"}>
                  <i id="dice" class="fas fa-dice"></i>
                </span>
                <span class="toggle-password ">
                  <i class="fas fa-eye" id="eye"></i>
                </span>
              </div>

              <div class="wrapper">
                <label for="id_url">URL</label>
                {{ form.url }}
              </div>

              <div class="wrapper">
                <label for="id_notes">Notes</label>
                {{ form.notes }}
              </div>
              
              <button class="btn btn-primary" type="submit">Add</button>
              <a href="{% url 'accounts' %}" class="btn btn-danger">Back</a>
          </form>
            
</div>


      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" data-bs-target="#exampleModalToggle2" data-bs-toggle="modal" >Open second modal</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

PasswordManager/manager/templates/manager/add_account.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block page_content %}
{% include 'navbar.html' %}
<div class="container">
    <h1>Create New Account Entry</h1>
    
    <form action="" method="post">
        {% csrf_token %}
        <div class="wrapper">
            <label for="title">Title</label>
            {{ form.title }}
        </div>
        
        <div class="wrapper">
            <label for="id_username">Username</label>
            {{ form.username }}
        </div>

        <div class="wrapper">
            <label for="id_email">Email</label>
            {{ form.email }}
        </div>
             
        <div class="wrapper password-field">
            <label for="id_password">Password</label>
            {{ form.password }}
            <span class="toggle-modal dice" data-bs-toggle="modal" data-bs-target="#"}>
                <a href="{% url 'generator' %}"><i id="dice" class="fas
                        fa-dice"></i></a>
            </span>
            <span class="toggle-password ">
                <i class="fas fa-eye-slash" id="eye"></i>
            </span>
        </div>

        <div class="wrapper">
            <label for="id_url">URL</label>
            {{ form.url }}
        </div>

        <div class="wrapper">
            <label for="id_notes">Notes</label>
            {{ form.notes }}
        </div>
        
        <button class="btn btn-primary" type="submit">Add</button>
        <a href="{% url 'accounts' %}" class="btn btn-danger">Back</a>
    </form>
            
</div>
{% endblock %}

PasswordManager/manager/templates/manager/edit_account.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block page_content %}

{% include 'navbar.html' %}
<div class="container">
    <h1>Edit {{ account.title }}</h1>
    
    <form action="" method="post">
        {% csrf_token %}
        <div class="wrapper">
            <label for="title">Title</label>
            {{ form.title }}
        </div>
        
        <div class="wrapper">
            <label for="id_username">Username</label>
            {{ form.username }}
        </div>

        <div class="wrapper">
            <label for="id_email">Email</label>
            {{ form.email }}
        </div>
             
        <div class="wrapper password-field">
            <label for="id_password">Password</label>
            {{ form.password }}
            <span class="toggle-modal dice" data-bs-toggle="modal" data-bs-target="#"}>
                <i id="dice" class="fas fa-dice"></i>
            </span>
            <span class="toggle-password ">
                <i class="fas fa-eye-slash" id="eye"></i>
            </span>
        </div>

        <div class="wrapper">
            <label for="id_url">URL</label>
            {{ form.url }}
        </div>

        <div class="wrapper">
            <label for="id_notes">Notes</label>
            {{ form.notes }}
        </div>
        
        <button class="btn btn-primary" type="submit">Edit</button>
        <a class="btn btn-danger" href="{% url 'accounts' %}">Back</a>
    </form>
            
</div>
{% endblock %}

PasswordManager/manager/templates/manager/generate.html
<div class="modal-dialog modal-dialog-centered" id="">
    <h1>This is the generator app</h1>
</div>

PasswordManager/manager/templates/manager/index.html
{% extends 'base.html' %}

{% block page_content %}

{% include 'navbar.html' %}

<div class="container">
    <h1>WELCOME</h1>
</div>

{% endblock %}

PasswordManager/manager/templates/manager/login_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block page_content %}
<div class="container text-center" >
        <div class="header-bar" style="padding-top: 150px;">
        <h1>Login</h1>
    </div>
    
    <div class="card-body">
        <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input class="button" type="submit" value="Login">
    </form>
    </div>
    
    
    
    <p>Don't have n account? <a href="{% url 'signup' %}">Register</a></p>
</div>
{% endblock %}

PasswordManager/manager/templates/manager/main.html
{% extends 'base.html' %}

{% block page_content %}

{% include 'navbar.html' %}


<div class="container">
    
    {% if user.is_authenticated %}

    <h2>Hello {{ user.username|capfirst }}</h2>

    <!-- MODAL BUTTON -->
    <!-- <a class="btn btn-secondary"href="{#% url 'new_account' %#}" data-bs-toggle="modal" data-bs-target="#exampleModalToggle">Crete Account</a> -->

    <a class="btn btn-secondary" href="{% url 'new_account' %}" >Crete Account</a>


    <br><br>

    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Username</th>
                <th>E-mail</th>
                <th>Password</th>
                <th>URL</th>
                <th>Notes</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for account in accounts %}
            <tr>
                <td>{{ account.title }}</td>
                <td><a class="tc to-clp" href="#" data={{ account.username }}>{{ account.username }}</a></td>
                <td><a class="tc to-clp" href="#" data={{ account.email }}>{{ account.email }}</a></td>


                <td>
                    <a class="tc to-clp" href="#" data={{ account.password }}>*********</a>
                </td>


                <td><a href="{{ account.url }}" target="_blank">{{ account.url }}</a></td> 
                <td>{{ account.notes|slice:":50" }}</td>
                <td>

                    <a class="btn btn-sm btn-secondary" href="{% url 'edit' account.id %}">Edit</a>

                    <form action="{% url 'delete' account.id %}" method="POST" style="display: inline;">
                        {% csrf_token %}
                        <button class="btn btn-danger btn-sm" type="submit" onclick="return confirm('Deleting this account will cause all of the information to be lost.\nDo you wish to continue?')">Delete</button></button>
                    </form>

                </td>
            </tr>

            {% endfor %}
        </tbody>
    </table>

    {% else %}
    <h1>You have no permission to be here</h1>
    {% endif %}
</div>

{#% include 'manager/add_account.html' %#}

{% endblock %}

PasswordManager/manager/templates/manager/sign_up_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block page_content %}
<div class="container">
    <div class="header-bar">
        <h1>Register</h1>
    </div>
        
    
    <div class="card-body">
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="button" type="submit" value="SignUp">
        </form>
    </div>
</div>

{% endblock %}

PasswordManager/manager/templates/navbar.html
<nav class="nav navbar navbar-expand-lg navbar-dark bg-dark justify-content-end">

    <div class="container">

      {% if user.is_authenticated %}
      <a class="navbar-brand" href="{% url 'accounts' %}">Password Vault</a>
      {% else %}
      <a class="navbar-brand" href="{% url 'index' %}">Password Vault</a> 
      {% endif %}

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">

          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'logout' %}" >LogOut</a>
          {% else %}
          <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Login</a>
          <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
          {% endif %}
          
        </div>
      </div>
    </div>
  </nav>